domain_path: C:\ANKUSH_Psuedo-Disk\AUV\hdmi\Zybo-Z7-20-HDMI-sw.ide\design_1_wrapper\export\design_1_wrapper\sw\domain_ps7_cortexa9_0
app_src_dir: E:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
